FROM ruby:3.4.1-alpine

LABEL version="2.0.2"
LABEL repository="https://github.com/brightsoftwares/blogpost-tools"
LABEL homepage="https://github.com/brightsoftwares/blogpost-tools"
LABEL maintainer="BrightSoftwares"

RUN apk add --no-cache git build-base
# Allow for timezone setting in _config.yml
RUN apk add --update tzdata
# Use curl to send API requests
RUN apk add --update curl

# debug
RUN bundle version

COPY LICENSE README.md /

COPY entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]
