# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

# Ruby 3.4+ no longer bundles these; Jekyll 4.3 still needs them.
gem 'base64'
gem 'bigdecimal'
gem 'csv'
gem 'logger'
gem 'webrick'
