FROM python:3.10-alpine

RUN apk update && apk upgrade --available && \
    apk add python3 python3-pip git cron dnsutils inetutils-ping curl -y 
RUN git clone https://github.com/pectojin/duplicati-client --depth 1 && \
       cd duplicati-client/ && ln -s /duplicati-client/duplicati_client.py /usr/bin/duc && pip3 install -r requirements.txt 
RUN curl -sSL https://get.docker.com/ | sh

    

# Copy the scripts to execute
RUN mkdir /scripts/
COPY *.sh /scripts/
RUN chmod 0644 /scripts/*.sh

# Copy hello-cron file to the cron.d directory
COPY hello-cron /etc/cron.d/hello-cron
#COPY backup-dbs /etc/cron.d/backup-dbs
#COPY backup-duplicati-jobs /etc/cron.d/backup-duplicati-jobs

# Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/hello-cron
#RUN chmod 0644 /etc/cron.d/backup-dbs
#RUN chmod 0644 /etc/cron.d/backup-duplicati-jobs

# Apply cron job
RUN crontab /etc/cron.d/hello-cron
#RUN crontab /etc/cron.d/backup-dbs
#RUN crontab /etc/cron.d/backup-duplicati-jobs
 
# Create the log file to be able to run tail
RUN touch /var/log/cron.log
 
# Run the command on container startup
CMD cron && tail -f /var/log/cron.log

#ADD entrypoint.sh /entrypoint.sh
#RUN chmod +x /entrypoint.sh
#
#ADD action.yml /action.yml
#
#ENTRYPOINT ["/entrypoint.sh"]
