name: "Translate posts into the desired language"

description: "You have posts written in markdown? You can translate them automatically into another language."

inputs:
  src_folder:
    description: The path to the folder where the posts to translate are located
  dest_folder:
    description: The path where you want to store the translated file.
  scan_folder:
    description: The path where you want to scan missing posts. Once found they will be generated in the dest_folder
  dry_run:
    type: boolean
    description: Whether to write translated files to disk or not.

outputs:
  updated_posts:
    description: A list of updated posts

runs:
  using: "docker"
  image: "Dockerfile"
