name: "Keyword suggestions to blogpost"

description: "Transform the keyword suggestions into markdown blog posts. Uses a seed of keywords."

inputs:
  src_folder:
    description: The folder where we will pull the blog post candidates from
    required: true
  dest_folder:
    description: The folder where we are going to generate the processed posts
    required: true
  dry_run:
    description: Whether we process it for real or just simulating
    default: false
  dest_lang:
    description: The destination language we will operate the summarization in.
    default: 'en'
  summarizer_minlength:
    description: Minimum sentence length.
    default: 60
  summarizer_nbsentences:
    description: The number of sentences we are going to generate.
    default: 25

  

outputs:
  dest_folder:
    description: The path to the the generated blog posts

runs:
  using: "docker"
  image: "Dockerfile"
