name: "Rename files to make it compliant with SEO"

description: "Rename the files to make them pretty"

inputs:
  source_path:
    description: The path to the folder where the draft posts are located
  wordpress_frontmatter:
    description: Set to true if you want to add frontmatter variables to push your post to wordpress with git-it-write
    default: False
    type: boolean
  

outputs:
  updated_posts:
    description: A list of updated posts

runs:
  using: "docker"
  image: "Dockerfile"
