name: "Rename files to make it compliant with SEO"

description: "Rename the files to make them pretty"

inputs:
  source_path:
    description: The path to the folder where the draft posts are located
  wordpress_frontmatter:
    description: Set to true if you want to add frontmatter variables to push your post to wordpress with git-it-write
    default: False
    type: boolean
  dry_run:
    description: Whether to save generated files
    default: false
  force_pretify:
    description: Whether to pretify file even if it is already pretified
    default: false
  siloterm_to_links_file:
    description: The csv file where we have the mapping between the silot term and the links
  siloterm_to_categories_file:
    description: The csv file where we have the mapping between the silot term and the categories
  default_author:
    description: Who should be the default author of the blog posts
  default_layout:
    description: What should be the default layout of the blog posts
  category_type:
    description: Does your site use categories or category to manage the categories
    default: category
  generate_silotermtolinksfile_if_missing:
    description: Should we generate the links mapping file if missing?
    default: false
  generate_silotermtocategoriesfile_if_missing:
    description: Should we generate categories mapping file if missing?
    default: false
  file_generation_src_path:
    description: Path to the folder where examples of files we can pull the mapping from. The script will read the posts in this folder and generate a mapping file silot_terms to categories or silot_terms to links. Then this mapping will be used to fill the category and links frontmatter values.
    
outputs:
  updated_posts:
    description: A list of updated posts

runs:
  using: "docker"
  image: "Dockerfile"
