name: "Latex CV"

description: "Generate CV using Latex."

inputs:
  src_folder:
    required: true
    description: The location of the main.tex file to compile 
  

outputs:
  dest_folder:
    description: The path to the the generated blog posts

runs:
  using: "docker"
  image: "Dockerfile"
