FROM ubuntu

RUN PROJECTDIR=$(pwd) && cd /tmp && wget http://ftp.fau.de/ctan/systems/texlive/tlnet/install-tl-unx.tar.gz && tar -xvzf install-tl-unx.tar.gz -C /tmp/myinstall_dir
WORKDIR /tmp/myinstall_dir
#cd install-tl-*
RUN chmod +x install-tl && ./install-tl --profile=$PROJECTDIR/texlive.profile
RUN PATH=/usr/local/texlive/2017/bin/x86_64-linux:$PATH
RUN pdflatex -v
WORKDIR $PROJECTDIR
