name: "Generate the internal linking opportunities"

description: "Generate the list of internal linking."

inputs:
  source_path:
    description: The path to the folder where the draft posts are located
  wordpress_frontmatter:
    description: Set to true if you want to add frontmatter variables to push your post to wordpress with git-it-write
    default: False
    type: boolean
    
  src_folder_toscan:
    description: The path to the folder where the markdown posts are stored.
  dst_folder_tosaveresults:
    description: The path to the folder where the analysis results will be saved
  internal_link_text_file:
    description: The full path to the csv file that contains examples of text that can be used in internal linking
  anchor_text_to_post:
    description: The full path to the csv file that contains an anchor text and a link to the post
  

outputs:
  updated_posts:
    description: A list of updated posts

runs:
  using: "docker"
  image: "Dockerfile"
