name: "Generate the internal linking opportunities"

description: "Generate the list of internal linking."

inputs:    
  src_folder_toscan:
    description: The path to the folder where the markdown posts are stored.
  dst_folder_tosaveresults:
    description: The path to the folder where the analysis results will be saved
  internal_link_text_file:
    description: The full path to the csv file that contains examples of text that can be used in internal linking
  anchor_text_to_post:
    description: The full path to the csv file that contains an anchor text and a link to the post
  aliases_yml_file:
    description: The full path to the aliases.yml file. This is not used for the moment.
  aliases_csv_file:
    description: The full path to the aliases.csv file that contains the mapping between the anchor text and the dst file
  aliasesfiltered_yml_file:
    description: Optional. Not used at the moment.
  dry_run:
    description: If true, the auto linked files won't be saved.
    default: false

outputs:
  updated_posts:
    description: A list of updated posts

runs:
  using: "docker"
  image: "Dockerfile"
