name: "OpenAI blog post generator"
description: "Generate blog posts based on prompts given to openai api"

inputs:

  channel:
    description: The channel where we are going to pull the post requirements from.
  posts_requests_base_url:
    description: The url to the api where we have the posts requirements. No trailing slash at the end.
  dst_generated_posts:
    description: The location where we are going to store the generated posts.
  max_retries:
    description: The number of time we are going to ask retry when openai fail.
    default: 5
  max_tokens:
    description: The maximum number of tokens to use for the generation of this post.
    default: 2500
  temperature:
    description: The higher this number, the more freestyle the content of the post will be.
    default: 0
  batch_size:
    description: The number of posts to process per run
    default: 5
  useexternal_prompt:
    description: Whether to use the prompt from the API or generate it locally
    default: false
  manually_generated_posts_channel:
    description: The channel of the posts that are generated manually

outputs:
  updated_posts:
    description: A list of updated posts

runs:
  using: "docker"
  image: "Dockerfile"
