name: "OpenAI blog post generator"

description: "Generate blog posts based on prompts given to openai api"

inputs:    

  keyword_suggestion_merged:

    description: The full path to the keyword suggestions merged csv file. This file should contain silot_terms and Suggestion columns. This file tells which keyword suggestion belongs to which silot_terms.

  src_interlinking_csv:

    description: The full path to the interlinking csv file. This file must contain the silot_terms and dst_file columns. This file tells which post file belongs to which silot terms.

  dst_aliases_file:

    description: The full path to the aliases.csv file where the result will be stored.

  

outputs:

  updated_posts:

    description: A list of updated posts

runs:

  using: "docker"

  image: "Dockerfile"
