name: Build and publish the MonicaHQ image

on:
  workflow_dispatch:
  push:
    paths:
      - 'monicahq-docker/**'
      
      
jobs:
  build-and-publish-monicahq-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

  docker:
    uses: BrightSoftwares/blogpost-tools/.github/workflows/build_and_publish_docker.yml@main
    with:
      image_name: bright-monicahq
      tag: latest
      subfolder_name: monicahq-docker
      dockerfile_name: Dockerfile
    secrets:
      registry_username: ${{ secrets.DOCKER_USERNAME }}
      registry_password: ${{ secrets.DOCKER_PASSWORD }}
