name: Build and publish the Backstage image

on:
  workflow_dispatch:
  push:
    paths:
      - 'backstage/**'
      
      
jobs:
  build-and-publish-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: backstage/backstage
          path: './backstage/public-backstage'

      - name: Check all files presence
        run: |
          echo "All folders"
          find -maxdepth 2 -type d -ls

          echo "All files"
          find -maxdepth 2 -type f -ls

          echo "Move the dockerfile under the public-backstage"
          mv backstage/Dockerfile backstage/public-backstage/

  docker:
    uses: BrightSoftwares/blogpost-tools/.github/workflows/build_and_publish_docker.yml@main
    with:
      image_name: bright-backstage
      tag: latest
      subfolder_name: backstage
      dockerfile_name: public-backstage/Dockerfile
    secrets:
      registry_username: ${{ secrets.DOCKER_USERNAME }}
      registry_password: ${{ secrets.DOCKER_PASSWORD }}
