name: Build and publish the Backstage image

on:
  workflow_dispatch:
  push:
    paths:
      - 'backstage/**'
      
      
jobs:
  build-and-publish-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: backstage/backstage
          path: './backstage-public'

      - name: Install using yarn
        run: |
          cd backstage-public
          yarn install --immutable
          yarn tsc
          yarn build:backend

      - name: Check all files presence
        run: |

          echo "All files"
          find -maxdepth 3 -ls

          echo "Move the dockerfile under the public-backstage"
          mv backstage/Dockerfile backstage-public/Dockerfile

          echo "After Dockerfile move All files"
          find -maxdepth 3 -ls

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: metaapi
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/bright-backstage
          flavor: |
            latest=true
            prefix=
            suffix=
          tags: |
            type=schedule
            type=ref,event=tag,enable=true,prefix=,suffix=
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
          
      - name: Build and push Docker image for API
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: "backstage-public"
          # file: ./backstage-public/Dockerfile
          no-cache: true
          push: true
          tags: ${{ steps.metaapi.outputs.tags }}
          labels: ${{ steps.metaapi.outputs.labels }}

  # docker:
  #   uses: BrightSoftwares/blogpost-tools/.github/workflows/build_and_publish_docker.yml@main
  #   needs: build-and-publish-docker
  #   with:
  #     image_name: bright-backstage
  #     tag: latest
  #     subfolder_name: backstage-public
  #     dockerfile_name: Dockerfile
  #     debug: true
  #   secrets:
  #     registry_username: ${{ secrets.DOCKER_USERNAME }}
  #     registry_password: ${{ secrets.DOCKER_PASSWORD }}
