name: Build and Publish Docker image
  
on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        type: string
      subfolder_name:
        type: string
        required: true
      dockerfile_name:
        type: string
        required: true
      debug:
        type: boolean
        default: false
    secrets:
      registry_username:
        required: true
      registry_password:
        required: true



jobs:
  build_and_push:
    name: Build and Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Debug - List files with depth 2
        if: ${{ inputs.debug }}
        run: |
          echo "Files in the folder ${{ inputs.subfolder_name }}"
          echo "Showing folders"
          # find ${{ inputs.subfolder_name }} -maxdepth 2 -type d -ls
          find -maxdepth 2 -type d -ls
          echo "Showing files"
          # find ${{ inputs.subfolder_name }} -maxdepth 2 -type f -ls
          find -maxdepth 2 -type f -ls
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.registry_username }}
          password: ${{ secrets.registry_password }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: metaapi
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ secrets.registry_username }}/${{ inputs.image_name }}
          flavor: |
            latest=true
            prefix=
            suffix=
          tags: |
            type=schedule
            type=ref,event=tag,enable=true,prefix=,suffix=
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
          
      - name: Build and push Docker image for API
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: "./${{ inputs.subfolder_name }}"
          file: ./${{ inputs.subfolder_name }}//${{ inputs.dockerfile_name }}
          push: true
          tags: ${{ steps.metaapi.outputs.tags }}
          labels: ${{ steps.metaapi.outputs.labels }}
          
