name: Build and publish the keyword suggestions image

env:
  subfolder: keyword-suggestion

on:
  workflow_dispatch:
  push:
    paths:
      - "${{ env.subfolder }}/**"
      
      
jobs:
  build-and-publish-keyword-suggestion:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one line script
        run: echo Hello from Github actions!

  docker:
    uses: BrightSoftwares/blogpost-tools/.github/workflows/build_and_publish_docker.yml@main
    with:
      image_name: keywordsuggestion
      tag: latest
      subfolder_name: ${{ env.subfolder }}
      dockerfile_name: Dockerfile.keywordsuggestion
    secrets:
      registry_username: ${{ secrets.DOCKER_USERNAME }}
      registry_password: ${{ secrets.DOCKER_PASSWORD }}
