# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish OpenAI posts generator Docker image

on:
  push:
    paths:
      - 'openai-generate-blogpost/**'
  workflow_dispatch:

env:
  SUBFOLDER: openai-generate-blogpost

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: metaapi
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: fullbright/openai-generate-blogpost
          flavor: |
            latest=true
            prefix=
            suffix=
          tags: |
            type=schedule
            type=ref,event=tag,enable=true,prefix=,suffix=
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      
      - name: Build and push Docker image for API
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        #working-directory: ./openai-generate-blogpost
        with:
          context: "./${{ env.SUBFOLDER }}"
          file: ./${{ env.SUBFOLDER }}/Dockerfile.openai
          push: true
          tags: ${{ steps.metaapi.outputs.tags }}
          labels: ${{ steps.metaapi.outputs.labels }}
          
      
