# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image

on:
  #release:
  #  types: [published]
  push:
    paths:
      - 'post-summarizer/**'
    #tags:
    #  - '*'
  workflow_dispatch:
  
#defaults:
#  run:
#    working-directory: ./post-summarizer

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: metaapi
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: fullbright/post-summarizer
          flavor: |
            latest=true
            prefix=
            suffix=
          tags: |
            type=schedule
            type=ref,event=tag,enable=true,prefix=,suffix=
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
          
      #- name: Extract metadata (tags, labels) for Docker
      #  id: metafrontend
      #  uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      #  with:
      #    images: fullbright/acceleratedtext-frontend
      #    flavor: |
      #      latest=true
      #      prefix=
      #      suffix=
      #    tags: |
      #      type=schedule
      #      type=ref,event=tag,enable=true,prefix=,suffix=
      #      type=ref,event=branch
      #      type=ref,event=pr
      #      type=semver,pattern={{version}}
      #      type=semver,pattern={{major}}.{{minor}}
      #      type=semver,pattern={{major}}
      #      type=sha
          
      #- name: Extract metadata (tags, labels) for Docker
      #  id: metadatomic
      #  uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      #  with:
      #    images: fullbright/acceleratedtext-datomic
      #    flavor: |
      #      latest=true
      #      prefix=
      #      suffix=
      #    tags: |
      #      type=schedule
      #      type=ref,event=tag,enable=true,prefix=,suffix=
      #      type=ref,event=branch
      #      type=ref,event=pr
      #      type=semver,pattern={{version}}
      #      type=semver,pattern={{major}}.{{minor}}
      #      type=semver,pattern={{major}}
      #      type=sha
          
      #- name: Extract metadata (tags, labels) for Docker
      #  id: metagf
      #  uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      #  with:
      #    images: fullbright/acceleratedtext-gf
      #    flavor: |
      #      latest=true
      #      prefix=
      #      suffix=
      #    tags: |
      #      type=schedule
      #      type=ref,event=tag,enable=true,prefix=,suffix=
      #      type=ref,event=branch
      #      type=ref,event=pr
      #      type=semver,pattern={{version}}
      #      type=semver,pattern={{major}}.{{minor}}
      #      type=semver,pattern={{major}}
      #      type=sha
      
      - name: Build and push Docker image for API
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        #working-directory: ./post-summarizer
        with:
          context: ".:post-summarizer"
          file: ./Dockerfile.postsummarizer
          push: true
          tags: ${{ steps.metaapi.outputs.tags }}
          labels: ${{ steps.metaapi.outputs.labels }}
          
      #- name: Build and push Docker image for Frontend
      #  uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      #  with:
      #    context: .
      #    file: ./Dockerfile.frontend
      #    push: true
      #    tags: ${{ steps.metafrontend.outputs.tags }}
      #    labels: ${{ steps.metafrontend.outputs.labels }}
          
      #- name: Build and push Docker image for Datomic
      #  uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      #  with:
      #    context: .
      #    file: ./Dockerfile.datomic
      #    push: true
      #    tags: ${{ steps.metadatomic.outputs.tags }}
      #    labels: ${{ steps.metadatomic.outputs.labels }}
          
      #- name: Build and push Docker image for gf
      #  uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      #  with:
      #    context: .
      #    file: ./Dockerfile.gf
      #    push: true
      #    tags: ${{ steps.metagf.outputs.tags }}
      #    labels: ${{ steps.metagf.outputs.labels }}
