name: Reusable Auto Internal Linking

on:
  workflow_call:
  workflow_dispatch:

jobs:
  internal_linking:
    runs-on: "${{ vars.RUNNER_LABEL || 'self-hosted' }}"
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Generate EN internal linking opportunities
        uses: BrightSoftwares/blogpost-tools/internal-linking@main
        continue-on-error: true
        with:
          src_folder_toscan: /github/workspace/_posts/en/
          dst_folder_tosaveresults: /github/workspace/_seo/internal-linking/en/
          internal_link_text_file: /github/workspace/_seo/internal-linking/internal_link_text.csv
          anchor_text_to_post: /github/workspace/_seo/internal-linking/en/anchor_text_to_post.csv
          aliases_yml_file: /github/workspace/_seo/internal-linking/en/aliases.yml
          aliases_csv_file: /github/workspace/_seo/internal-linking/en/aliases.csv
          dry_run: false
          aliases_new_csv_file: /github/workspace/_seo/internal-linking/en/aliases.csv
          lang: en

      - name: Markdown linting on EN posts
        uses: BrightSoftwares/blogpost-tools/markdown-linting@main
        continue-on-error: true
        with:
          folder_to_lint: /github/workspace/_posts/en/

      - name: Generate FR internal linking opportunities
        uses: BrightSoftwares/blogpost-tools/internal-linking@main
        continue-on-error: true
        with:
          src_folder_toscan: /github/workspace/_posts/fr/
          dst_folder_tosaveresults: /github/workspace/_seo/internal-linking/fr/
          internal_link_text_file: /github/workspace/_seo/internal-linking/internal_link_text.csv
          anchor_text_to_post: /github/workspace/_seo/internal-linking/fr/anchor_text_to_post.csv
          aliases_yml_file: /github/workspace/_seo/internal-linking/fr/aliases.yml
          aliases_csv_file: /github/workspace/_seo/internal-linking/fr/aliases.csv
          dry_run: false
          aliases_new_csv_file: /github/workspace/_seo/internal-linking/en/aliases.csv
          lang: fr

      - name: Markdown linting on FR posts
        uses: BrightSoftwares/blogpost-tools/markdown-linting@main
        continue-on-error: true
        with:
          folder_to_lint: /github/workspace/_posts/fr/

      - name: Commit changes if any
        run: |
          CHANGES_EXIST="$(git status --porcelain | wc -l)"
          echo "There are $CHANGES_EXIST changes to commit"
          if [ "$CHANGES_EXIST" -eq 0 ]; then
            echo "No changes to commit"
          else
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "generated and changed files"
            git pull --rebase
            git push
          fi
