name: Generate keyword suggestions on a weekly basis

on:
  #push:
  #  branches:
  #      - master
  workflow_dispatch:
  workflow_call:
    inputs:
      generatenewkeywordsuggestions_keywordseed: 
        required: true
        type: string
        default: /github/workspace/_drafts/keywords.csv
      generatenewkeywordsuggestions_keywordsuggestionsgenerationfolder: 
        required: true
        type: string
        default: /github/workspace/_drafts
      generatenewkeywordsuggestions_draftspath: 
        required: true
        type: string
        default: /github/workspace/_drafts/
      generatenewkeywordsuggestions_keywordsuggestionsblogpostfile: 
        required: true
        type: string
        default: keyword_suggestions_merged_blogpost_candidates.csv
      generatenewkeywordsuggestions_keywordminvolumeeligible: 
        required: true
        type: string
        default: 1
      generatenewkeywordsuggestions_keywordmaxvolumeeligible: 
        required: true
        type: string
        default: 500000
      #generateblogpostcandidatesdata10_100_srcfolder: 
      #  required: true
      #  type: string
      #  default: /github/workspace/_drafts/
      generateblogpostcandidatesdata_srcfolder: 
        required: true
        type: string
        default: /github/workspace/_drafts/
      generateblogpostcandidatesdata10_100_keywordsuggestiongenerationfolder: 
        required: true
        type: string
        default: /github/workspace/_drafts/
      generateblogpostcandidatesdata10_100_keywordsuggestiongenerationfile: 
        required: true
        type: string
        default: /github/workspace/_drafts/keyword_suggestions.csv
      generateblogpostcandidatesdata10_100_keywordsuggestionsblogpostfile: 
        required: true
        type: string
        default: /github/workspace/_drafts/kw_blogpost_candidates_10_100.csv
      generateblogpostcandidatesdata10_100_keywordminvolumeeligible: 
        required: true
        type: string
        default: 10
      generateblogpostcandidatesdata10_100_keywordmaxvolumeeligible:
        required: true
        type: string
        default: 100
      #generateblogpostcandidatesdata100_500_srcfolder: 
      #  required: true
      #  type: string
      #  default: /github/workspace/_drafts/
      generateblogpostcandidatesdata100_500_keyword_suggestion_generation_folder: 
        required: true
        type: string
        default: /github/workspace/_drafts/
      generateblogpostcandidatesdata100_500_keyword_suggestion_generation_file: 
        required: true
        type: string
        default: /github/workspace/_drafts/keyword_suggestions.csv
      generateblogpostcandidatesdata100_500_keyword_suggestions_blogpost_file: 
        required: true
        type: string
        default: /github/workspace/_drafts/kw_blogpost_candidates_100_500.csv
      generateblogpostcandidatesdata100_500_keyword_min_volume_eligible: 
        required: true
        type: string
        default: 100
      generateblogpostcandidatesdata100_500_keyword_max_volume_eligible: 
        required: true
        type: string
        default: 500
      suggestionstoblogpost10_100_keyword_suggestions_generation_folder: 
        required: true
        type: string
        default: /github/workspace/_drafts
      suggestionstoblogpost10_100_keyword_suggestion: 
        required: true
        type: string
        default: kw_blogpost_candidates_10_100.csv
      suggestionstoblogpost10_100_drafts_path: 
        required: true
        type: string
        default: /github/workspace/_drafts/
      suggestionstoblogpost10_100_keyword_seed: 
        required: true
        type: string
        default: /github/workspace/_drafts/keywords.csv
      suggestionstoblogpost10_100_batch_size: 
        required: true
        type: string
        default: 5
      suggestionstoblogpost10_100_language: 
        required: true
        type: string
        default: fr
      suggestionstoblogpost100_500_keywordsuggestionsgenerationfolder: 
        required: true
        type: string
        default: /github/workspace/_drafts
      suggestionstoblogpost100_500_keywordsuggestion: 
        required: true
        type: string
        default: kw_blogpost_candidates_10_100.csv
      suggestionstoblogpost100_500_draftspath: 
        required: true
        type: string
        default: /github/workspace/_drafts/
      suggestionstoblogpost100_500_keywordseed: 
        required: true
        type: string
        default: /github/workspace/_drafts/keywords.csv
      suggestionstoblogpost100_500_batchsize: 
        required: true
        type: string
        default: 5
      suggestionstoblogpost100_500_language: 
        required: true
        type: string
        default: fr
      generatenewyoutubevids_srcfolder: 
        required: true
        type: string
        default: /github/workspace/_drafts/
      generatenewyoutubevids_ytsearchresultsfile: 
        required: true
        type: string
        default: /github/workspace/_drafts/youtube_search_results.csv
      generatenewyoutubevids_ytalreadyusedvids: 
        required: true
        type: string
        default: /github/workspace/_drafts/youtube_videos_used.csv
      generatenewyoutubevids_language: 
        required: true
        type: string
        default: fr
      generatenewyoutubevids_country: 
        required: true
        type: string
        default: fr
      generatenewyoutubevids_youtubevideoduration: 
        required: true
        type: string
        default: medium
      transcribeytvideos_draftspath: 
        required: true
        type: string
        default: /github/workspace/_drafts/
      forced_to_run_on_github:
        required: false
        type: string
        default: false

      
    secrets:
      #unsplash_access_key:
      #  required: true
      #cloudinary_url:
      #  required: true
      generatenewyoutubevids_youtubeapikey: 
        required: true
        #default: ${{ secrets.YOUTUBE_API_KEY }}
        #type: string

jobs:
  check-runner:
    runs-on: ubuntu-latest
    outputs:
      runner-label: ${{ steps.set-runner.outputs.runner-label }}

    steps:
      - name: Set runner
        id: set-runner
        uses: BrightSoftwares/blogpost-tools/check-runner@main
        env:
          CHECK_RUNNER_TOKEN: ${{ secrets.CHECK_RUNNER_ACCESS_TOKEN }}
          GITHUB_REPO_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          FORCE_RUNS_ON_UBUNTU: ${{ inputs.forced_to_run_on_github }}
      
  jekyll:
    # runs-on: ubuntu-latest
    # runs-on: self-hosted
    needs: check-runner
    runs-on: ${{ needs.check-runner.outputs.runner-label }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Generate new keyword suggestions
        uses: BrightSoftwares/blogpost-tools/keyword-suggestion@main
        with:
          keyword_seed: ${{ inputs.generatenewkeywordsuggestions_keywordseed }} # /github/workspace/_drafts/keywords.csv
          keyword_suggestions_generation_folder: ${{ inputs.generatenewkeywordsuggestions_keywordsuggestionsgenerationfolder }} # /github/workspace/_drafts
          drafts_path: ${{ inputs.generatenewkeywordsuggestions_draftspath }} # /github/workspace/_drafts/
          keyword_suggestions_blogpost_file: ${{ inputs.generatenewkeywordsuggestions_keywordsuggestionsblogpostfile }} # keyword_suggestions_merged_blogpost_candidates.csv
          keyword_min_volume_eligible: ${{ inputs.generatenewkeywordsuggestions_keywordminvolumeeligible }} # 1
          keyword_max_volume_eligible: ${{ inputs.generatenewkeywordsuggestions_keywordmaxvolumeeligible }} # 500000

      - name: Intermediary commit to save generated keywords
        run: |
          # date > generated.txt
          CHANGES_EXIST="$(git status --porcelain | wc -l)"
          echo "There are $CHANGES_EXIST changes to commit"
          if [ "$CHANGES_EXIST" -eq 0 ]; then
            echo "There are no changes to commit"
          else
            echo "Committing changes"
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "generated and changed files"
            git pull --rebase
            git push
          fi
          
      - name: Generate blog post candidates data 10-100
        uses: BrightSoftwares/blogpost-tools/blogpost-candidates-generation@main
        with:
        
          src_folder: ${{ inputs.generateblogpostcandidatesdata_srcfolder }} # /github/workspace/_drafts/
          keyword_suggestion_generation_folder: ${{ inputs.generateblogpostcandidatesdata10_100_keywordsuggestiongenerationfolder }} # /github/workspace/_drafts/
          keyword_suggestion_generation_file: ${{ inputs.generateblogpostcandidatesdata10_100_keywordsuggestiongenerationfile }} # /github/workspace/_drafts/keyword_suggestions.csv
          keyword_suggestions_blogpost_file: ${{ inputs.generateblogpostcandidatesdata10_100_keywordsuggestionsblogpostfile }} # /github/workspace/_drafts/kw_blogpost_candidates_10_100.csv
          keyword_min_volume_eligible: ${{ inputs.generateblogpostcandidatesdata10_100_keywordminvolumeeligible }} # 10
          keyword_max_volume_eligible: ${{ inputs.generateblogpostcandidatesdata10_100_keywordmaxvolumeeligible }} # 100
          
      
      - name: Generate blog post candidates data 100-500
        uses: BrightSoftwares/blogpost-tools/blogpost-candidates-generation@main
        with:
        
          src_folder: ${{ inputs.generateblogpostcandidatesdata_srcfolder }} # /github/workspace/_drafts/
          keyword_suggestion_generation_folder: ${{ inputs.generateblogpostcandidatesdata100_500_keyword_suggestion_generation_folder }} # /github/workspace/_drafts/
          keyword_suggestion_generation_file: ${{ inputs.generateblogpostcandidatesdata100_500_keyword_suggestion_generation_file }} # /github/workspace/_drafts/keyword_suggestions.csv
          keyword_suggestions_blogpost_file: ${{ inputs.generateblogpostcandidatesdata100_500_keyword_suggestions_blogpost_file }} # /github/workspace/_drafts/kw_blogpost_candidates_100_500.csv
          keyword_min_volume_eligible: ${{ inputs.generateblogpostcandidatesdata100_500_keyword_min_volume_eligible }} # 100
          keyword_max_volume_eligible: ${{ inputs.generateblogpostcandidatesdata100_500_keyword_max_volume_eligible }} # 500
          
      - name: Suggestions to blogpost 10-100
        uses: BrightSoftwares/blogpost-tools/suggestions-to-blogpost@main
        with:
          keyword_suggestions_generation_folder: ${{ inputs.suggestionstoblogpost10_100_keyword_suggestions_generation_folder }} # /github/workspace/_drafts
          keyword_suggestion: ${{ inputs.suggestionstoblogpost10_100_keyword_suggestion }} # kw_blogpost_candidates_10_100.csv
          drafts_path: ${{ inputs.suggestionstoblogpost10_100_drafts_path }} # /github/workspace/_drafts/
          keyword_seed: ${{ inputs.suggestionstoblogpost10_100_keyword_seed }} # /github/workspace/_drafts/keywords.csv
          batch_size: ${{ inputs.suggestionstoblogpost10_100_batch_size }} # 5
          language: ${{ inputs.suggestionstoblogpost10_100_language }} # fr
          
      - name: Suggestions to blogpost 100-500
        uses: BrightSoftwares/blogpost-tools/suggestions-to-blogpost@main
        with:
          keyword_suggestions_generation_folder: ${{ inputs.suggestionstoblogpost100_500_keywordsuggestionsgenerationfolder }} # /github/workspace/_drafts
          keyword_suggestion: ${{ inputs.suggestionstoblogpost100_500_keywordsuggestion }} # kw_blogpost_candidates_100_500.csv
          drafts_path: ${{ inputs.suggestionstoblogpost100_500_draftspath }} # /github/workspace/_drafts/
          keyword_seed: ${{ inputs.suggestionstoblogpost100_500_keywordseed }} # /github/workspace/_drafts/keywords.csv
          batch_size: ${{ inputs.suggestionstoblogpost100_500_batchsize }} # 5
          language: ${{ inputs.suggestionstoblogpost100_500_language }} # fr
          
      - name: Generate new youtube vids
        uses: BrightSoftwares/blogpost-tools/youtube-vid-finder@main
        with:
          src_folder: ${{ inputs.generatenewyoutubevids_srcfolder }} # /github/workspace/_drafts/
          youtube_api_key: ${{ secrets.generatenewyoutubevids_youtubeapikey }} # ${{ secrets.YOUTUBE_API_KEY }}
          yt_search_results_file: ${{ inputs.generatenewyoutubevids_ytsearchresultsfile }} # /github/workspace/_drafts/youtube_search_results.csv
          yt_already_used_vids: ${{ inputs.generatenewyoutubevids_ytalreadyusedvids }} # /github/workspace/_drafts/youtube_videos_used.csv
          language: ${{ inputs.generatenewyoutubevids_language }} # fr
          country: ${{ inputs.generatenewyoutubevids_country }} # fr
      
      - name: transcribe-yt-videos
        uses: BrightSoftwares/blogpost-tools/transcript-downloader@main
        with:
          drafts_path: ${{ inputs.transcribeytvideos_draftspath }} # /github/workspace/_drafts/

      - name: Compress too big files and remove them
        run: |
          echo "Compressing the 2 big files"
          tar zcvf ${{ inputs.generateblogpostcandidatesdata10_100_keywordsuggestiongenerationfolder }}kw_blogpost_candidates_10_100.csv.tar.gz ${{ inputs.generateblogpostcandidatesdata10_100_keywordsuggestiongenerationfolder }}kw_blogpost_candidates_10_100.csv
          tar zcvf ${{ inputs.generateblogpostcandidatesdata100_500_keyword_suggestion_generation_folder }}kw_blogpost_candidates_100_500.csv.tar.gz ${{ inputs.generateblogpostcandidatesdata100_500_keyword_suggestion_generation_folder }}kw_blogpost_candidates_100_500.csv
          echo "Compression done"
          ls -lah _drafts/

      - name: Ignore files that are bigger than 50Mb
        run: |
          #echo "Ignore files that are bigger than 50Mb"
          #find . -size +50M | cat >> .gitignore
          #cat .gitignore
          echo "Delete the files that are bigger than +50Mb"
          find -type f \( -name "kw_blogpost_candidates_*" \) -size +50M -delete
          
      - run: |
          # date > generated.txt
          CHANGES_EXIST="$(git status --porcelain | wc -l)"
          echo "There are $CHANGES_EXIST changes to commit"
          if [ "$CHANGES_EXIST" -eq 0 ]; then
            echo "There are no changes to commit"
          else
            echo "Committing changes"
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "generated and changed files"
            git pull --rebase
            git push
          fi
