name: Publish Rss to Blogpost Docker image

on:
  push:
    paths:
      - 'news-to-blogpost/**'
  workflow_dispatch:

env:
  SUBFOLDER: news-to-blogpost

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: metaapi
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: fullbright/news-to-blogpost
          flavor: |
            latest=true
            prefix=
            suffix=
          tags: |
            type=schedule
            type=ref,event=tag,enable=true,prefix=,suffix=
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      
      - name: Build and push Docker image for API
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: "./${{ env.SUBFOLDER }}"
          file: ./${{ env.SUBFOLDER }}/Dockerfile.unsplash
          push: true
          tags: ${{ steps.metaapi.outputs.tags }}
          labels: ${{ steps.metaapi.outputs.labels }}
          
      
